<a href="https://colab.research.google.com/github/Boyidi-Sahithi/fml-lab/blob/main/Numpy_practice.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
a=np.array([1,2,3])
print(type (a))
print(a)
print(a.shape)

<class 'numpy.ndarray'>
[1 2 3]


In [ ]:
import numpy as np
b=np.zeros((2,2))
print(b)
c=np.ones((1,2))
print(c)
d=np.full((2,2),6)
print(d)
e=np.eye(2)
print(e)


[[0. 0.]
 [0. 0.]]
[[1. 1.]]
[[6 6]
 [6 6]]
[[1. 0.]
 [0. 1.]]


In [ ]:
import numpy as np
e=np.random.random((2,2))
print(e)

[[0.50492784 0.63917158]
 [0.15221151 0.97158718]]


In [ ]:
import numpy as np
a=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print(a)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [ ]:
import numpy as np
v = np.array([1,2,3])
w = np.array([4,5])

print(np.reshape(v, (3, 1)) * w)


[[ 4  5]
 [ 8 10]
 [12 15]]


In [ ]:
import numpy as np
x = np.array([[1,2,3], [4,5,6], [7,8,9], [10, 11, 12]])
v = np.array([1, 0, 1])
y = np.empty_like(x)  
for i in range(4):
    y[i, :] = x[i, :] + v

print(y)

[[ 2  2  4]
 [ 5  5  7]
 [ 8  8 10]
 [11 11 13]]


In [ ]:
import numpy as np
x = np.array([[1,2],[3,4]])
y = np.array([[5,6],[7,8]])

v = np.array([9,10])
w = np.array([11, 12])
print(v.shape, w.shape)
print(v.dot(w))
print(np.dot(v, w))

print(x.dot(y))


(2,) (2,)
219
219
[[19 22]
 [43 50]]
